version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

root:
  level: ${LOG_LEVEL:-INFO}
  handlers: [console]

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false
