app:
  name: Doxie
  env: development
  debug: true
  port: 8000

logging:
  level: INFO
  config_file: config/logging.yaml

# Confluence uses model defaults unless overridden by env vars
confluence:
  cloud: true
  verify_ssl: true
